- hosts: terraform-ansible
  tasks:
    - name: Instalando o Python, virtualenv
      apt: 
        pkg:
        - python3
        - virtualenv
        update_cache: yes
      become: yes

    - name: Instalando depencias com pip(Djando e Django Rest) 
      pip: 
        virtualenv: /home/ubuntu/tcc/venv
        name: 
          - django
          - djangorestframework

    - name : Verificando se o projeto existe
      stat: 
        path: /home/ubuntu/tcc/setup/settings.py
      register: projeto


    - name : Iniciando o projeto
      shell: '. /home/ubuntu/tcc/venv/bin/activate; django-admin startproject setup /home/ubuntu/tcc/'
      when: not projeto.stat.exists
    - name:  Alterando o hosts do settings.py
      lineinfile: 
        path: /home/ubuntu/tcc/setup/settings.py 
        regexp: 'ALLOWED_HOSTS'
        line: 'ALLOWED_HOSTS = ["*"]'
        backrefs: yes  
